### ISSUE TITLE
pdnsd: error network is unreachable

### ISSUE THREAD

**Issue by hillz1** [SAPikachu/pdnsd#2]
edited

**Comment by SAPikachu** [comment]
This means your router is not (properly) connected to Internet. There may be an issue in your routing table, or maybe your proxy went wrong again. Can you confirm that your redsocks configuration is working first?

**Comment by hillz1** [comment]
What is the iptables command to redirect that DNS to port 12345 (redsocks port) ?

**Comment by SAPikachu** [comment]
OK I noticed an issue in your config, as far as I know redsocks doesn't support ICMP, so `uptest=ping` will always fail. Try changing to `uptest=none; preset=on;`?

**Comment by SAPikachu** [comment]
(No response for 6 days so I assume it has been resolved.)

**Comment by hillz1** [comment]
Hi mate, sorry I got really busy for the past few days, I'll be back working on it by tomorrow night, please don't close it yet.

**Comment by SAPikachu** [comment]
Sure, let me know when you are back. :)

**Comment by hillz1** [comment]
Sure I will

**Comment by hillz1** [comment]
Hi, I tried your advice above but still no luck, the problem might not related to pdnsd but I'm still trying to figure out what's wrong, right now I'm gonna close this issue but if I need to ask about something again please let me open another one. Thanks for all the help so far mate.

**Comment by SAPikachu** [comment]
OK, no problem. :)
